name: Build/release Electron app

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ${{ matrix.os }}
    permissions:
      actions: read
      contents: write

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: build-linux
        if: matrix.os == 'ubuntu-latest'
        run: pnpm build:linux

      - name: build-mac
        if: matrix.os == 'macos-latest'
        run: pnpm build:mac

      - name: build-win
        if: matrix.os == 'windows-latest'
        run: pnpm build:win

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: cliff.toml
          args: -vv --latest --strip header
        env:
          OUTPUT: CHANGES.md
          GITHUB_REPO: ${{ github.repository }}

      - name: release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          name: ${{ github.ref }}
          tag_name: ${{ github.ref }}
          body: ${{ steps.git-cliff.outputs.content }}
          files: |
            dist/*.exe
            dist/*.zip
            dist/*.dmg
            dist/*.AppImage
            dist/*.snap
            dist/*.deb
            dist/*.rpm
            dist/*.tar.gz
            dist/*.yml
            dist/*.blockmap
